"""Shared owner console presentation, with readable review and media layouts."""

CSS = r'''
:root{color-scheme:light;--soft:#5b6f7b;--bad:#a44448;--accent-2:#4f9779}
:root{--bg:#f4f6f8;--surface:#fff;--surface-2:#fff;--text:#192733;--muted:#627180;--line:#e1e6eb;--line-strong:#cdd6de;--accent:#276759;--good:#207351;--warn:#946019;--danger:#a44448}
body{background:var(--bg);color:var(--text);font-size:15px;line-height:1.6}
.wrap{max-width:1600px;margin:0 auto;padding:0 36px 44px 250px}
.top{position:fixed;inset:0 auto 0 0;width:212px;box-sizing:border-box;display:flex;flex-direction:column;align-items:stretch;justify-content:flex-start;padding:34px 20px;background:#fff;border-right:1px solid var(--line);border-bottom:0;z-index:30}
.brand{font-size:18px;letter-spacing:-.04em;color:#1a453d;margin-bottom:38px;padding:0 10px}.brand:before{content:'▶';display:inline-grid;place-items:center;width:27px;height:27px;border-radius:8px;background:#e6f1ed;color:#276759;margin-right:9px;font-size:11px}
.nav{display:flex;flex-direction:column;align-items:stretch;gap:6px}.nav>a,.nav-more>summary{padding:12px 14px;border-radius:10px;font-size:14px;color:#657280;font-weight:650}.nav a.active,.nav a[aria-current=page]{background:#e9f2ee;color:#215b4c;border-color:transparent}.nav a:hover,.nav-more>summary:hover{background:#f0f4f5;color:#192733}.nav-more{margin-top:22px;border-top:1px solid var(--line);padding-top:14px}.nav-more-menu{position:static;min-width:0;background:#f6f8f9;border:0;box-shadow:none;margin-top:6px}.nav-more-menu a{color:#53616c;font-size:13px}
main{padding-top:36px}.hero{margin:0 0 26px;padding:0;gap:20px}.hero h1{font-size:32px;letter-spacing:-.045em;line-height:1.18;color:#192733;margin:6px 0 10px}.eyebrow,.section-kicker{color:#527e70;font-size:11px;letter-spacing:.12em}.muted,.tiny,.metrics-note,.media-note{color:#627180}.hero .muted{max-width:660px;font-size:15px}
.card,.job,.ready-card,.automation-card,.channel-summary,.notice,.overview-video{background:#fff;border:1px solid var(--line);box-shadow:0 2px 5px rgba(35,52,70,.025);border-radius:15px}.card{padding:24px}.notice{color:#42515d;background:#fffdf8;border-color:#ebe0c7}.notice b{color:#574728}.notice p{color:#75674f}.automation-card h2{color:#203b35}.automation-card p{color:#627180}.workflow-strip li{background:#f1f6f3;color:#3b6355;border-color:#dbe7df}
.btn,button{background:#276759;border-color:#276759;color:#fff;box-shadow:none;border-radius:9px;padding:10px 16px;font-weight:700;font-size:13px}.btn:hover,button:hover{background:#205547}.btn.secondary{background:#fff;border-color:#d8e0e5;color:#334b5b}.btn.secondary:hover{background:#f4f7f8}.btn.repair,.btn.danger{background:#fff7e9;color:#865f2c;border-color:#e9d9bb}.btn.success{background:#edf6ef;color:#286743;border-color:#cee3d4}
.overview-top{grid-template-columns:minmax(0,1.7fr) minmax(260px,1fr);gap:20px}.overview-counts{gap:14px;margin:22px 0}.overview-count{background:#fff;border:1px solid var(--line);border-radius:13px;padding:19px 22px;color:#213645}.overview-count b{font-size:30px;color:#244d41}.overview-count small{color:#73818c}.overview-section{margin-top:28px}.overview-heading h2,.history-label h2,.metrics-head h2{font-size:19px;letter-spacing:-.025em;color:#203442}.overview-video{padding:16px 20px}.overview-video-title{color:#233644}.overview-video-meta{color:#74818a}.overview-footer{color:#7b8991}
.channel-summary{padding:20px}.channel-summary h3{font-size:16px;color:#213a34}.channel-numbers b{font-size:24px;color:#253f38}.channel-numbers span{color:#708079}.channel-schedule{border-color:#e6ece8;color:#586b60}.channel-schedule span{font-size:12px}.metrics-head{margin-bottom:14px}.metrics-note{font-size:12px}.channel-overview{gap:16px}
.review-tabs{display:flex;gap:6px;flex-wrap:wrap;padding:5px;background:#e9edef;border-radius:12px;margin:22px 0}.review-tabs a{padding:9px 17px;border-radius:8px;font-size:13px;font-weight:700;color:#66747d}.review-tabs a[aria-current=page]{background:#fff;color:#265a4c;box-shadow:0 1px 4px #d8e0e5}.review-tabs b{margin-left:7px;font-size:11px;opacity:.7}
.review-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.review-card{min-width:0;padding:18px;background:#fff;border:1px solid var(--line);border-radius:16px}.review-card.has-media{display:grid;grid-template-columns:150px minmax(0,1fr);gap:18px}.review-preview{background:#12201d;border-radius:12px;overflow:hidden;display:flex;align-items:center;justify-content:center;min-height:220px;position:relative}.review-preview video{display:block;width:100%;height:267px;object-fit:contain}.review-preview.audio{min-height:100px;padding:14px;background:#edf4f0;grid-column:1/-1}.review-preview audio{width:100%;max-width:100%}.review-card.has-audio{display:block}.review-meta{display:flex;gap:8px;flex-wrap:wrap;color:#7b898f;font-size:11px;margin-bottom:9px}.review-card h2{font-size:16px;line-height:1.4;letter-spacing:-.015em;margin:7px 0 12px;color:#223b34}.review-body{min-width:0;display:flex;flex-direction:column}.review-reason{font-size:13px;line-height:1.65;color:#65747c;margin:0 0 12px}.review-actions{display:flex;align-items:center;gap:9px;margin-top:auto;padding-top:10px;flex-wrap:wrap}.review-actions a{font-size:12px}.review-kind{display:inline-flex;align-self:flex-start;background:#eef4f1;color:#44705c;border-radius:6px;padding:3px 8px;font-size:10px;font-weight:800}.review-kind.warning{background:#fff3dd;color:#8a6829}.review-empty{display:flex;gap:12px;align-items:center;padding:12px;background:#f6f8f9;border-radius:10px;font-size:12px;color:#7c8991;margin-bottom:12px}.review-empty:before{content:'▷';font-size:26px;color:#a0adae}.review-footnote{font-size:12px;color:#7d8991;margin:14px 0 24px}.review-video-error{font-size:12px;color:#745c37;background:#fff6e9;padding:12px;border-radius:8px}.review-video-error[hidden]{display:none}
.review-summary{display:flex;align-items:center;justify-content:space-between;gap:20px;margin:26px 0 16px}.review-summary h2{font-size:18px;margin:0;color:#263f36}.review-summary p{font-size:12px;color:#73817c;margin:3px 0}.review-summary a{color:#376953;font-size:13px}.review-search{display:flex;gap:10px;align-items:center;margin:0 0 20px}.review-search input{max-width:360px;background:#fff;color:#273d35;border:1px solid var(--line);border-radius:10px;padding:11px 14px;font-size:13px}.review-search button{padding:10px 15px}
.badge,.state.ready,.state.completed,.state.rendered,.state.private,.state.public{background:#edf4f1;color:#3b6c56;border-color:#d6e5dc}.state.attention,.state.failed,.state.repair{background:#fff0d5;color:#8e641e}.state.running{background:#eaf0fb;color:#3e638a}.delivery-badges{gap:5px}.delivery-badges .state{font-size:10px;padding:4px 8px}.job-title,.ready-title{color:#223b34}.job-status,.job-meta,.ready-fact span{color:#627180}.ready-fact{background:#f6f8f9;border-color:var(--line)}.ready-fact b{color:#7b8890}.technical-details,.history-archive,.archive-details{background:#f8fafb;border-color:var(--line);color:#6a7880}.technical-body,code{color:#56636d}.result-media-head h2{color:#273d35}.result-video-frame{background:#101b19;border:0}.result-video{max-height:600px}.back-links a{color:#3c6e5c}input,select,textarea{background:#fff;color:#263b34;border-color:#d6e0dd}.empty{background:#fff;color:#708077;border:1px dashed #d5dfdb}.library-filter{color:#5e746b;background:#fff;border-color:#dce5e1}.library-filter[aria-current=page]{color:#285e4b;background:#edf4ef;border-color:#bdd6c7}.progress{background:#e9efec}.bar{background:#4f9779}
.overview-top .notice{background:#fffdf8;border-color:#ebe0c7}.overview-top .notice h2{color:#574728}.overview-count span{color:#506476}.overview-count:hover,.overview-video:hover{background:#edf3f0;border-color:#c8dbd2}.automation-card .section-kicker,.overview-heading a{color:#527e70}.workflow-strip li:before{color:#527e70;border-color:#a5bfb3}.nav a:nth-child(n+4){display:block}.wrap input[type=text],.wrap input[type=password],.wrap input[type=url],.wrap textarea,.wrap select{background:#fff;color:#263b34}.wrap label.field{color:#415d51}.choice input:checked+label{background:#edf5ef;border-color:#71a18a;box-shadow:0 0 0 2px #e0ede6}.technical-body,.detail-body,.guidance,.service,.performance-cell{background:#f7f9fa;color:#536772}.notice.error{background:#fff0ef;color:#934441;border-color:#e8c9c5}.notice.success{background:#edf6ef;color:#286743;border-color:#cee3d4}.state.unreviewed,.state.review,.state.manual{background:#fff0d5;color:#8e641e}
.result-media{background:#fff;border-color:var(--line);padding:16px}.result-media-head h2{color:#273d35}.result-media .review-preview video{height:auto;max-height:65vh;min-height:260px}.video-identity{color:#637b71}.job-panel>.result-action{margin-top:16px}.review-options{margin-top:18px;color:#708078;font-size:13px}.review-options summary{cursor:pointer}.review-options .result-action{margin-top:12px}.operations-status{border-top:1px solid var(--line);padding-top:13px;margin-top:15px;font-size:12px;color:#627180}.operations-status b{color:#2d6450}.operations-status.stale b,.operations-status.blocked b{color:#946019}
@media(max-width:760px){.review-search{flex-wrap:wrap}.review-search input[name=q]{flex:1 0 100%;width:100%;max-width:none;box-sizing:border-box}.review-search select{flex:1;min-width:0;width:auto}.result-media .review-preview video{max-height:60vh}.job-panel{padding:18px}.hero h1{overflow-wrap:anywhere}}
.profile-details>summary,.profile-grid label{color:#536c61}.profile-grid input,.profile-grid textarea,.profile-grid select{background:#fff;color:#273d35}.badge.good,.badge.ready{background:#edf6ef;color:#286743;border-color:#cee3d4}.brief-full,pre{background:#f7f9fa;color:#536772}.review-preview{color-scheme:dark}
@media(min-width:1600px){.top{left:max(0px,calc((100vw - 1600px)/2))}}
@media(max-width:1100px){.review-grid{grid-template-columns:1fr}.wrap{padding-left:228px;padding-right:24px}.overview-top{grid-template-columns:1fr}.top{width:204px}}
@media(max-width:760px){.wrap{padding:0 18px 30px}.top{position:relative;inset:auto;width:auto;padding:16px 0 12px;display:block;border-right:0;border-bottom:1px solid var(--line);background:transparent}.brand{display:inline-block;font-size:17px;margin:0 0 12px;padding:0}.nav{flex-direction:row;gap:4px;flex-wrap:wrap}.nav>a,.nav-more>summary{font-size:12px;padding:8px 10px}.nav-more{margin:0;padding:0;border:0}.nav-more-menu{position:absolute;right:0;min-width:170px;background:#fff;border:1px solid var(--line);box-shadow:0 8px 20px #dbe2e6}main{padding-top:24px}.hero h1{font-size:28px}.hero .muted{font-size:14px}.overview-counts{grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.overview-count{display:block;padding:12px}.overview-count b{font-size:25px;display:block}.overview-count span{font-size:12px}.overview-count small{display:none}.review-tabs{gap:2px}.review-tabs a{font-size:12px;padding:8px 10px}.review-tabs b{margin-left:3px}.review-card.has-media{grid-template-columns:118px minmax(0,1fr);gap:13px;padding:13px}.review-preview video{height:210px}.review-preview{min-height:210px}.review-card h2{font-size:14px}.review-reason{font-size:12px}.review-meta{font-size:10px}.review-actions .btn{padding:8px 10px;font-size:11px}.review-summary{align-items:flex-start;gap:10px}.review-search input{min-width:0;flex:1}.channel-overview{grid-template-columns:1fr}.overview-hero>.btn{display:none}}
'''

# The fixed navigation must scroll independently on short laptop windows.
# Keep form controls in the document flow, including at 200% browser zoom.
CSS += r'''
html{min-height:100%;overflow-y:auto;scroll-padding-top:20px}
body{min-width:0;min-height:100dvh;overflow-x:clip}
.top{max-height:100dvh;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin;padding:28px 18px}
.top .brand{margin-bottom:26px;flex-shrink:0}.top .nav{min-height:0;flex-shrink:0}
main{min-width:0;overflow-wrap:break-word;padding-top:28px}
.wrap{min-width:0}.hero{margin-bottom:20px}.hero h1{font-size:30px}.hero p{margin:6px 0 0}
.settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;align-items:start;max-width:1080px}
.settings-grid>.card{margin:0}.settings-grid h2{font-size:19px}.settings-grid p{font-size:14px;line-height:1.55}
.settings-links{display:grid;margin-top:12px}.settings-links>a{display:grid;gap:3px;padding:15px 0;border-top:1px solid var(--line)}
.settings-links>a:first-child{border-top:0}.settings-links>a:hover b{color:var(--accent)}.settings-links span{font-size:13px;color:var(--muted)}
.settings-grid form{margin:0}.settings-grid button{width:100%;margin-top:8px}
.provider-panel{width:100%;max-width:680px}.provider-panel .card{padding:22px}.provider-panel form{margin:0}
.provider-panel button{width:100%;margin-top:12px}.provider-panel .notice{margin-bottom:16px}
.provider-panel h2{font-size:18px}.provider-panel .provider-help{font-size:13px;color:var(--muted);margin:16px 0}
.overview-shortcuts{margin:0;padding:20px}.overview-shortcuts h2{font-size:17px}.overview-shortcuts .settings-links{margin-top:0}.overview-shortcuts .settings-links>a{padding:10px 0}
.funding-details{margin:16px 0;border:1px solid var(--line);border-radius:12px;background:white}.funding-details>summary{padding:13px 17px;cursor:pointer;color:var(--muted);font-size:13px}.funding-details .notice{margin:0 14px 14px;border-radius:10px}
@media(max-width:760px){.overview-top{gap:12px;margin-bottom:12px}.automation-card{padding:18px}.automation-card h2{font-size:20px;margin:6px 0}.automation-card p{font-size:13px;margin-top:5px}.operations-status{padding-top:9px;margin-top:10px}.overview-shortcuts{display:none}.overview-counts{margin:14px 0}.overview-section{margin-top:20px}}
@media(max-height:650px) and (min-width:761px){.top{padding-top:18px;padding-bottom:18px}.top .brand{margin-bottom:16px}.nav>a{padding:9px 12px}main{padding-top:20px}.hero h1{font-size:27px}.card{padding:20px}}
@media(max-width:1000px){.settings-grid{grid-template-columns:1fr}}
@media(max-width:760px){.top{max-height:none;overflow:visible;padding:15px 0 12px}.top .brand{margin-bottom:10px}.nav{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));overflow:visible}.nav>a{font-size:12px;text-align:center;padding:8px 5px;white-space:normal}.nav a:nth-child(n+4){display:block}.wrap{padding:0 14px 36px}main{padding-top:20px}.hero{margin-bottom:18px}.hero h1{font-size:27px}.settings-grid{gap:14px}.provider-panel .card{padding:18px}}
'''
